---
-
  become: true
  hosts: localhost
  name: "Install logstash"
  tasks:
    -
      name: "install elasticsearch rpm key"
      shell: "rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    -
      copy:
        content: "[logstash-6.x] \n\
            name=Elastic repository for 6.x packages  \n\
            baseurl=https://artifacts.elastic.co/packages/6.x/yum \n\
            gpgcheck=1 \n\
            gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch \n\
            enabled=1 \n\
            autorefresh=1 \n\
            type=rpm-md \n"
        dest: /etc/yum.repos.d/logstash.repo
    -
      name: "install elasticsearch rpm key"
      shell: "yum install logstash -y"
  
